// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview An AI agent that recommends courses based on student interests and academic history.
 *
 * - recommendCourses - A function that recommends courses to students.
 * - RecommendCoursesInput - The input type for the recommendCourses function.
 * - RecommendCoursesOutput - The return type for the recommendCourses function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const RecommendCoursesInputSchema = z.object({
  interests: z
    .string()
    .describe('The interests of the student, comma separated.'),
  academicHistory: z
    .string()
    .describe('The academic history of the student, comma separated.'),
  courses: z
    .string()
    .describe('The courses available, comma separated.'),
});

export type RecommendCoursesInput = z.infer<typeof RecommendCoursesInputSchema>;

const RecommendCoursesOutputSchema = z.object({
  recommendedCourses: z
    .string()
    .describe('The recommended courses for the student, comma separated.'),
});

export type RecommendCoursesOutput = z.infer<typeof RecommendCoursesOutputSchema>;

export async function recommendCourses(input: RecommendCoursesInput): Promise<RecommendCoursesOutput> {
  return recommendCoursesFlow(input);
}

const prompt = ai.definePrompt({
  name: 'recommendCoursesPrompt',
  input: {schema: RecommendCoursesInputSchema},
  output: {schema: RecommendCoursesOutputSchema},
  prompt: `You are an AI assistant that recommends courses to students based on their interests and academic history.

  Student Interests: {{{interests}}}
  Student Academic History: {{{academicHistory}}}
  Available Courses: {{{courses}}}

  Please recommend courses that are relevant to the student's interests and academic history.
  Respond with just the comma separated names of the courses.`,
});

const recommendCoursesFlow = ai.defineFlow(
  {
    name: 'recommendCoursesFlow',
    inputSchema: RecommendCoursesInputSchema,
    outputSchema: RecommendCoursesOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
